---
title: Introduction to Computational Social Science
description: "GESIS Fall Seminar, 2024"
author: 
  - name: John McLevey
    email: john.mclevey@uwaterloo.ca
    affiliations:
      - name: University of Waterloo
  - name: Johannes Gruber
    email: j.b.gruber@uva.nl
    affiliations:
      - name: University of Amsterdam
date: 02/28/2024
date-modified: last-modified
---

## Course Description

## Learning Objectives

## Readings

## Research Software

This course is offered in both Python (with [John](about.qmd#john-mclevey-(python-course)) and R (with [Johannes](about.qmd#johannes-gruber-(r-course)). You can find details on installing and setting up the required research software [here](software.qmd).

## Course Project

## Course Schedule

|  | Module | Dates | Reading | Python Course | R Course |
|:-- |:-------|:------|:------|:--------|:-----------|
| 1 | [Introduction](../modules/Module-01.qmd) | XXXX | [Module Notebook](../textbook/chapters/1-introduction.qmd) | [Python Slides](../python-slides/Python-01.qmd) | [R Slides](../r-slides/R-01.qmd) |
| 2 | [Collecting and Working with Data](../modules/Module-02.qmd) | XXXX | [Module Notebook](../textbook/chapters/2-collecting-working-with-data.qmd) | [Python Slides](../python-slides/Python-02.qmd) | [R Slides](../r-slides/R-01.qmd) |
| 3 | [Computational Text Analysis](../modules/Module-03.qmd) | XXXX | [Module Notebook](../textbook/chapters/3-computational-text-analysis.qmd) | [Python Slides](../python-slides/Python-03.qmd) | [R Slides](../r-slides/R-01.qmd) |
| 4 | [Computational Network Analysis](../modules/Module-04.qmd) | XXXX | [Module Notebook](../textbook/chapters/4-computational-network-analysis.qmd) | [Python Slides](../python-slides/Python-04.qmd) | [R Slides](../r-slides/R-01.qmd) |
| 5 | [Social Simulation & Agent-based Models](../modules/Module-05.qmd) | XXXX | [Module Notebook](../textbook/chapters/5-simulation-abms.qmd) | [Python Slides](../python-slides/Python-05.qmd) | [R Slides](../r-slides/R-01.qmd) |
| 6 | [Conclusion](../modules/Module-06.qmd) | XXXX | [Module Notebook](../textbook/chapters/6-conclusion.qmd) | [Python Slides](../python-slides/Python-06.qmd) | [R Slides](../r-slides/R-01.qmd) |

